### ISSUE TITLE
When will the repair be done?

### ISSUE THREAD

**Issue by WrongProgram1** [TERMUXID3/email-sender#1]
![Screenshot_2020_0506_220440](https://user-images.githubusercontent.com/49438078/81186653-a1058e00-8fe5-11ea-84e7-178436f287da.png)

**Comment by JessyDelta** [comment]
kapan bang perbaikannya selesai

**Comment by N74NK** [comment]
> kapan bang perbaikannya selesai

Kita ganti server, itu servernya jelek jarang work jadi tunggu aja ya.

**Comment by JessyDelta** [comment]
oke bang klo udah fix langsung kasih inform saya ya bang
